### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by MatthiasRMS** [mverzilli/crystalla#13]
Hi ! 

I'm trying to require crystalla in a small script but it crashes at the require.

```
Error in eig.cr:1: while requiring "crystalla"

require "crystalla"
^

in lib/crystalla/src/crystalla.cr:1: while requiring "./crystalla/*"

require "./crystalla/*"
^

Syntax error in lib/crystalla/src/crystalla/lib_blas.cr:4: expecting identifier 'end', not 'else'

  else
  ^
```

Since there isn't a lot of users yet, it's hard to find answers elsewhere. Is this a common issue ? 

My shard.yml:

```
dependencies:
  crystalla:
    github: mverzilli/crystalla
```

Any idea ? 

Thanks a lot

**Comment by mverzilli** [comment]
Hi! Sorry that you stumbled upon this, it's apparently related to the removal of `ifdef` from the language at 0.20.0: https://github.com/crystal-lang/crystal/issues/2710

I'm working on upgrading the lib, but this caught me in the middle of migrating my computer. I'll fix it soon.

**Comment by mverzilli** [comment]
Fixed through https://github.com/mverzilli/crystalla/commit/2a71338a332e3b28623f8ece023a382035ef5f50.

At least with this you get all the functionality and passing specs. I had to turn off SVD calls to Lapack, because I'm probably missing something. Will get back to this soon. 

Let me know how it goes!

**Comment by MatthiasRMS** [comment]
Indeed, it solved it ! thanks a lot. Are you still planning on maintaining this library ? I'm interested in contributing to provide more linear algebra functions and classic machine learning algorithms, but wouldn't want to spend time if it's not maintained. As you wrote in the readMe, I'd get ideas and inspirations from Numpy to bring more features to Crystalla

**Comment by mverzilli** [comment]
Absolutely! I think the next step for Crystalla is to add an nd array which at least provides the same features that we currently support in `Matrix`, but if you find yourself wanting any other features that would make sense here let's discuss it!

**Comment by MatthiasRMS** [comment]
Great ! If you think that's the priority then I can do it. 
I was also thinking of adding more features present in the [linealg](https://docs.scipy.org/doc/scipy-0.18.1/reference/linalg.html) module (norms, eigenvalues etc). 
 
But first I'll take a look at the nd array and what could be done !

**Comment by mverzilli** [comment]
If you want to explore adding linealg features that's great also! Currently you'll be limited by the lack of nd arrays, but if there's a subset that you can make work on Matrices and if you cover the features with specs, it should be easy to extend to nd arrays later. Pick whatever makes you happier :).
